POST http://localhost:3001/api/mensajes/portfolio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2E5OGQwNWE3ODk2ZmQ1NzMwM2E3MCIsInVzZXJuYW1lIjoiTWloYSIsImlhdCI6MTY2ODk3OTY5OH0.pSeSRshiEePBV8RFuO-lXqENaio7osYSBP6GjuspxK8

{
  "asunto": "Relleno de mihaiku",
  "email": "portafolio@mihaiku.com",
  "contenido": "Mensaje de relleno"

}